SELECT 
    HISTORY_CAR.HISTORY_ID,
    IF (ISNULL(HISTORY_CAR.DURATION_TYPE), 
        HISTORY_CAR.DATE_DIFF * HISTORY_CAR.DAILY_FEE,
        ROUND(HISTORY_CAR.DATE_DIFF * (100 - PLAN.DISCOUNT_RATE) * HISTORY_CAR.DAILY_FEE / 100, 0)) AS FEE
FROM
    (
        SELECT
            HISTORY.HISTORY_ID,
            CAR.CAR_TYPE,
            CAR.DAILY_FEE,
            DATEDIFF(END_DATE, START_DATE) + 1 AS DATE_DIFF,
            CASE 
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
                ELSE NULL
            END AS DURATION_TYPE
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
        JOIN
            CAR_RENTAL_COMPANY_CAR AS CAR
        ON
            HISTORY.CAR_ID = CAR.CAR_ID
    ) AS HISTORY_CAR
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON
    HISTORY_CAR.CAR_TYPE = PLAN.CAR_TYPE AND
    HISTORY_CAR.DURATION_TYPE = PLAN.DURATION_TYPE
WHERE
    HISTORY_CAR.CAR_TYPE LIKE '트럭'
ORDER BY
    FEE DESC, HISTORY_ID DESC
