WITH COUNT_USERS AS (
    SELECT  YEAR(JOINED) AS YEAR, COUNT(USER_ID) AS TOTAL
    FROM    USER_INFO
    WHERE   JOINED LIKE '2021%'
)


SELECT  
        YEAR(SALES_DATE) AS YEAR, 
        MONTH(SALES_DATE) AS MONTH, 
        COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT USER_ID) / COUNT_USERS.TOTAL, 1) AS PURCHASED_RATIO
FROM    ONLINE_SALE
JOIN    COUNT_USERS
ON      YEAR = COUNT_USERS.YEAR
WHERE   USER_ID IN  (
                        SELECT  USER_ID
                        FROM    USER_INFO
                        WHERE   JOINED LIKE '2021%'
                    )
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC
