WITH COUNT_REVIEW 
AS (
        SELECT      MEMBER_ID,
                    COUNT(REVIEW_ID) AS COUNTS
        FROM        REST_REVIEW
        GROUP BY    MEMBER_ID
   )

SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM
    (MEMBER_PROFILE AS MEMBER JOIN REST_REVIEW AS REVIEW ON MEMBER.MEMBER_ID = REVIEW.MEMBER_ID)
    JOIN
    COUNT_REVIEW ON MEMBER.MEMBER_ID = COUNT_REVIEW.MEMBER_ID
WHERE
    COUNTS = (SELECT MAX(COUNTS) FROM COUNT_REVIEW)
ORDER BY
    REVIEW_DATE ASC, REVIEW_TEXT ASC
