-- 회원 이름, 리뷰 텍스트, 리뷰 작성일(YYYY-MM-DD)
-- 리뷰 최다 작성자의 리뷰들 조회
-- 리뷰 작성일 오름차순 / 리뷰 텍스트 오름차순

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R
ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID = ( -- 리뷰 최다 작성자의 MEMBER_ID 구하기
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
