-- APPOINTMENT : PT_NO, MDDR_ID(=DR_ID)
-- 2022년 04월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역 조회
-- 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시
-- 진료예약일시 오름차순 정렬

-- 1. APNT_YMD=2022-04-13, APNT_CNCL_YN=N
-- 2. MCDP_CD=CS
SELECT APNT.APNT_NO, PT.PT_NAME, PT.PT_NO, APNT.MCDP_CD, DR_NAME, APNT.APNT_YMD
# SELECT APNT.APNT_NO, PT.PT_NAME, PT.PT_NO, APNT.MCDP_CD, APNT.APNT_YMD
FROM APPOINTMENT AS APNT
INNER JOIN PATIENT AS PT
ON PT.PT_NO=APNT.PT_NO
INNER JOIN DOCTOR AS DR
ON DR.DR_ID=APNT.MDDR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND APNT_CNCL_YN="N"
ORDER BY APNT_YMD ASC;

# SELECT APNT_NO, DR_NAME, APNT_YMD, APNT_CNCL_YN
# FROM APPOINTMENT
# INNER JOIN DOCTOR
# ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
# ORDER BY APNT_YMD DESC;
# WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = DATE_FORMAT('2022-04-13', '%Y-%m-%d')
# WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
# AND APNT_CNCL_YN="N"
