-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, "%Y-%m-%d")
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MP.MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
        FROM MEMBER_PROFILE MP
        JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
        GROUP BY MP.MEMBER_ID
    ) AS T
    WHERE RNK = 1
)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT
;
