-- 코드를 입력하세요
SELECT COUNT(USER_ID) into @user_count FROM USER_INFO WHERE YEAR(JOINED) = 2021;

SELECT YEAR(B.SALES_DATE) YEAR,
        MONTH(B.SALES_DATE) MONTH,
        COUNT(DISTINCT B.USER_ID) PUCHASED_USERS,
        ROUND(1.00 * COUNT(DISTINCT B.USER_ID) / @user_count, 1) PUCHASED_RATIO
FROM USER_INFO A
JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = 2021
GROUP BY 1, 2
ORDER BY 1, 2
;
