# 상반기, 7월
# FH FLAVOR(PK), SHIPMENT_ID(FK)
# JULY SHIPMENT_ID(PK), FLAVOR(FK)
# JULY : 같은 맛이라도 다른 출하 번호를 가질 수 있음
# 7월 아이스크림 총 주문량, 상반기 아이스크림 총 주문량의 합산이 큰 순서대로 상위 3개의 맛 조회

# SUM(FIRST_HALF.TOTAL_ORDER + JULY.TOTAL_ORDER)
# ORDER BY SUM DESC

SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
INNER JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) AS JL
ON FH.FLAVOR = JL.FLAVOR
ORDER BY (FH.TOTAL_ORDER + JL.TOTAL_ORDER) DESC
LIMIT 3;
