SELECT 
    C1.CAR_ID,
    C1.CAR_TYPE,
    ROUND(C1.DAILY_FEE * 30 * (100 - C3.DISCOUNT_RATE) / 100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS C1
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C2
ON 
    C1.CAR_ID = C2.CAR_ID
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C3
ON
    C1.CAR_TYPE = C3.CAR_TYPE
WHERE
    C1.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
    )
    AND C3.DURATION_TYPE = '30일 이상'
GROUP BY
    C1.CAR_ID
HAVING
    C1.CAR_TYPE IN ('세단', 'SUV') AND
    FEE BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;
