SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) JULY ON FIRST_HALF.FLAVOR = JULY.FLAVOR
ORDER BY (JULY.TOTAL_ORDER + FIRST_HALF.TOTAL_ORDER) DESC
LIMIT 3
