# 자동차 종류 : 세단 OR SUV
# 대여기간 : 2022-11-01 ~ 2022-11-30
# 대여금액 : 50만원 이상, 200만원 미만
# CAR ID, CAR_TYPE, FEE(총 대여 금액)
# ORDER BY FEE 내림차순, CAR_TYPE 오름차순, CAR_ID 내림차순

SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE = '30일 이상'
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
AND CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY    
    # 이렇게 해야 기간 제대로 구해짐
    WHERE START_DATE < '2022-11-30'
    AND END_DATE > '2022-11-01'
    # WHERE START_DATE >= '2022-11-01' AND END_DATE <= '2022-11-30'
    # 위 쿼리문의 경우 조건문이 각각 시행되어 
    # END_DATE = '2022-10-21'도 SELECT 됨
)
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC
