-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS as i
JOIN ANIMAL_OUTS as o
ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.SEX_UPON_INTAKE LIKE 'INTACT%'
AND (o.SEX_UPON_OUTCOME LIKE 'SPAYED%' OR o.SEX_UPON_OUTCOME LIKE 'NEUTERED%')
ORDER BY ANIMAL_ID;
