-- SALE(판매중), RESERVED(예약중), DONE(거래완료)
-- 게시글 ID 내림차순 정렬
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
CASE 
    WHEN (STATUS = "SALE") THEN "판매중"
    WHEN (STATUS = "RESERVED") THEN "예약중"
    ELSE "거래완료"
END AS STATUS
FROM USED_GOODS_BOARD AS BOARD
WHERE DATE_FORMAT(CREATED_DATE, "%Y-%m-%d") = "2022-10-05"
ORDER BY BOARD_ID DESC;
