# 2022.03 온/오프 판매날짜, 상품ID, 유저ID, 판매량
# OFFLINE_SALE의 USER_ID는 NULL로 표시
# 판매일 오름차순, 상품ID 오름차순, 유저ID 오름차순

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, IFNULL(NULL, NULL) AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE AS OFFS
WHERE '2022-03' = DATE_FORMAT(SALES_DATE,'%Y-%m')
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE AS ONS
WHERE '2022-03' = DATE_FORMAT(SALES_DATE,'%Y-%m')
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
