SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN
    (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
     FROM JULY
     GROUP BY FLAVOR) AS J
ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.JULY_TOTAL DESC
LIMIT 3;
