-- 코드를 입력하세요
SET @RN = 0;

SELECT CONCAT("/home/grep/src/", B.BOARD_ID, "/", B.FILE_ID, B.FILE_NAME, B.FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID, @RN := @RN + 1 AS RN
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC ) AS A
JOIN USED_GOODS_FILE AS B 
ON A.BOARD_ID = B.BOARD_ID
WHERE A.RN = 1
ORDER BY B.FILE_ID DESC
;
